<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QTB4BMV" failures="1" tests="11" name="com.dryrun.testcases.LoginPageTest" time="37.205" errors="0" timestamp="2024-11-15T20:31:18 IST" skipped="0">
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyAIroastamaniLogo" time="0.138"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyTitle" time="0.016">
    <failure message="expected [ART - ADMI] but found [ART - ADMIN]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [ART - ADMI] but found [ART - ADMIN]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.dryrun.testcases.LoginPageTest.verifyTitle(LoginPageTest.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyTitle -->
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyemailtext" time="0.032"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifypasswordtext" time="0.027"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyusrnameRequiredtext" time="0.778"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifypasswordRequiredtext" time="0.249"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyusernamenotvalidtext" time="3.456"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyInvalidUserandPwdtext" time="8.214"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyInvalidUserandPwdtext" time="8.084"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyInvalidUserandPwdtext" time="7.936"/>
  <testcase classname="com.dryrun.testcases.LoginPageTest" name="verifyLoginsuccess" time="8.275"/>
</testsuite> <!-- com.dryrun.testcases.LoginPageTest -->
